events {
    worker_connections 1024;
}

http {
    upstream inspetor_backend {
        server inspetor-app:3000;
    }

    # Servidor para inspetor.terpens.com.br:9444
    server {
        listen 9444 ssl;
        server_name inspetor.terpens.com.br;

        ssl_certificate /etc/nginx/ssl/inspetor.terpens.com.br.crt;
        ssl_certificate_key /etc/nginx/ssl/inspetor.terpens.com.br.key;

        location / {
            proxy_pass http://inspetor_backend;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }

    # Servidor para inspetor.terpens.com.br:3001 (HTTP)
    server {
        listen 3001;
        server_name inspetor.terpens.com.br;

        location / {
            proxy_pass http://inspetor_backend;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}
